##### **Length of a vector**

In [6]:
import numpy as np

def compute_vector_length(vector):
    square_sum = np.sum(vector ** 2, axis=0)
    vector_length = np.sqrt(square_sum)
    return vector_length

arr = np.array([1, 2, 3])
print(f'Vector length: {compute_vector_length(arr)}')

Vector length: 3.7416573867739413


##### **Dot product**

In [7]:
import numpy as np

def compute_dot_product(vector1, vector2):
    dot_product = vector1.dot(vector2)
    return dot_product

arr_1 = np.array([1, 2, 3])
arr_2 = np.array([8, 9, 10])
print(f'Dot product: {compute_dot_product(arr_1, arr_2)}')

Dot product: 56


##### **Multiplying a vector by matrix**

In [8]:
import numpy as np

def matrix_multi_vector(matrix, vector):
    result = np.matmul(matrix, vector)
    return result

matrix = np.array([
    [1, 2, 3],
    [1, 2, 3],
    [1, 2, 3]
])

vector = np.array([1, 2, 3])
result = matrix_multi_vector(matrix, vector)
print(result) 

[14 14 14]


##### **Multiplying a matrix by a matrix**

In [9]:
import numpy as np

def matrix_multi_matrix(matrix1, matrix2):
    result = np.matmul(matrix1, matrix2)
    return result

matrix1 = np.array([
    [1, 2, 8],
    [1, 0, 3],
    [9, 2, 3]
])

matrix2 = np.array([
    [11, 22, 3],
    [1, 29, 3],
    [1, 2, 33]
])

result = matrix_multi_matrix(matrix1, matrix2)
print(result)

[[ 21  96 273]
 [ 14  28 102]
 [104 262 132]]


##### **Matrix inverse**

**Inverse matrix of A**
$$ A = \left(\begin{array}{cc} -2 & 6 \\ 8 & -4 \end{array}\right)$$
$$ det(A) = -4.-2 + 8.6 = 56\Rightarrow det(A) \neq 0$$
**So $A$ is invertible, we can have inverse matrix of $A$ is:**
$$ A^{-1} = \frac{1}{det(A)}.\left(\begin{array}{cc} -4 & -6 \\ -8 & -2 \end{array}\right) = \frac{1}{56}.\left(\begin{array}{cc} -4 & -6 \\ -8 & -2 \end{array}\right) = \left(\begin{array}{cc} 0.1 & 0.15 \\ 0.2 & 0.05 \end{array}\right)$$

In [10]:
import numpy as np

def inverse_matrix(matrix):
    inverse = np.linalg.inv(matrix)
    return inverse

matrix = np.array([
    [-2, 6],
    [8, -4],
])

inverse = inverse_matrix(matrix)
print(inverse)

[[0.1  0.15]
 [0.2  0.05]]
