##### **Question 1**

In [3]:
import numpy as np
arr = np.arange(0, 10, 1)
print(f"Numpy Array: {arr}")

Numpy Array: [0 1 2 3 4 5 6 7 8 9]


##### **Question 2**

In [8]:
arr_1 = np.ones((3, 3)) > 0
arr_2 = np.ones((3, 3), dtype=bool)
arr_3 = np.full((3, 3), fill_value=True, dtype=bool)

if np.array_equal(arr_1, arr_2) and np.array_equal(arr_2, arr_3):
    print("They are equal")
else:
    print("They are not equal")
print(f"Result:\n {arr_1}")

They are equal
Result:
 [[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


##### **Question 3**

In [10]:
import numpy as np
arr = np.arange(0, 10)
print(arr[arr%2 == 1])

[1 3 5 7 9]


##### **Question 4**

In [11]:
import numpy as np
arr = np.arange(0, 10)
arr[arr%2 == 1] = -1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


##### **Question 5**

In [12]:
import numpy as np
arr = np.arange(10)
arr_2d = arr.reshape(2, -1)
print(arr_2d)

[[0 1 2 3 4]
 [5 6 7 8 9]]


##### **Question 6**

In [13]:
import numpy as np
arr_1 = np.arange(10).reshape(2, -1)
arr_2 = np.arange(10).reshape(2, -1)
c = np.concatenate([arr_1, arr_2], axis=0)
print("Result: \n", c)

Result: 
 [[0 1 2 3 4]
 [5 6 7 8 9]
 [0 1 2 3 4]
 [5 6 7 8 9]]


##### **Question 7**

In [1]:
import numpy as np
arr_1 = np.arange(10).reshape(2, -1)
arr_2 = np.repeat(1, 10).reshape(2, -1)
c = np.concatenate([arr_1, arr_2], axis=1)
print("C = ", c)

C =  [[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


##### **Question 8**

In [2]:
import numpy as np
arr = np.array([1, 2, 3])
print(np.repeat(arr, 3))
print(np.tile(arr, 3))

[1 1 1 2 2 2 3 3 3]
[1 2 3 1 2 3 1 2 3]


##### **Question 9**

In [3]:
import numpy as np
a = np.array([2, 6, 1, 9, 10, 3, 27])
index = np.where((a>=5)&(a<=10))
print(index)

(array([1, 3, 4], dtype=int64),)


##### **Question 10**

In [4]:
import numpy as np

def max_x(x, y):
    if x >= y:
        return x
    else:
        return y

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

pair_max = np.vectorize(max_x, otypes=[float])
print(pair_max(a, b))

[6. 7. 9. 8. 9. 7. 5.]


##### **Question 11**

In [5]:
import numpy as np

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

print("Result", np.where(a<b, b, a))

Result [6 7 9 8 9 7 5]
