##### **Function Definition**

In [9]:
import matplotlib.image as mpimg
import numpy as np

def lightness_method(image):
    max = np.max(image, axis=2, keepdims=True)
    min = np.min(image, axis=2, keepdims=True)
    lightness = (max + min) / 2
    return lightness

def average_method(image):
    average = np.mean(image, axis=2, keepdims=True)
    return average

def luminosity_method(image):
    luminosity = 0.21 * image[:, :, 0] + 0.72 * image[:, :, 1] + 0.07 * image[:, :, 2]
    return np.expand_dims(luminosity, axis=-1)

##### **Question 1**

In [3]:
import matplotlib.image as mpimg
img = mpimg.imread('./materials/dog.jpeg')
gray_img_01 = lightness_method(img)
gray_img_01[0, 0]

array([102.5])

##### **Question 2**

In [4]:
import matplotlib.image as mpimg
img = mpimg.imread('./materials/dog.jpeg')
gray_img_02 = average_method(img)
gray_img_02[0, 0]

array([107.66666667])

##### **Question 3**

In [10]:
import matplotlib.image as mpimg
img = mpimg.imread('./materials/dog.jpeg')
gray_img_03 = luminosity_method(img)
gray_img_03[0, 0]

array([126.23])